### ISSUE TITLE
Takiyo Summoning

### ISSUE THREAD

**Issue by dwightdrafts** [annakins/Katana#4]
I encountered an issue with Takiyo spawning every time I get on my horse when I don't have Katana as a follower. I have another follower mod Auri who also has a animal they summon. It's not that annoying considering I don't ride my horse that often but I wanted to make this issue known. If I find away to resolve this I will update this.

**Comment by annakins** [comment]
Hello! Thanks so much for sharing this issue. Totally overlooked this one!

Just started a new game, rode a horse, and I didn't see Takiyo summoned. 
Please let me know if this update fixes this oopsie in your game: https://github.com/annakins/Katana/releases/tag/0.44

**Comment by dwightdrafts** [comment]
> Hello! Thanks so much for sharing this issue. Totally overlooked this one!
> 
> Just started a new game, rode a horse, and I didn't see Takiyo summoned. Please let me know if this update fixes this oopsie in your game: https://github.com/annakins/Katana/releases/tag/0.44

**Comment by dwightdrafts** [comment]
The update resolved the issue thank you!
